### ISSUE TITLE
htmlwidget

### ISSUE THREAD

**Issue by paulgovan** [timelyportfolio/rCharts_512paths#4]
Hi @timelyportfolio 

I'm a big fan of your buildingwidgets.com. Have you ever thought about turning this into an htmlwidgets.org with additional functionality? This is the sweetest "what-if" analysis ever.

-Paul

**Comment by timelyportfolio** [comment]
Great to hear from you and glad you are enjoying buildingwidgets.  I have thought about it, but very concerned about the gray area also mentioned in #3 since this is from the very commercial New York Times with no license assigned.  I love it too and would love to see it applied to decision trees and brackets in a general manner, but I've been very careful to only select MIT or other R-suitable open source licenses.

**Comment by paulgovan** [comment]
You make a good point, and I've come across this issue myself. Thanks again for the widgets and keep up the good work!
